/**
 * Returns department names based on `nameUrl` key
 */

export const departmentNameByNameUrl = {
  crafts: "Arts - Hobbies - Crafts",
  children: "Babies - Children - Toys",
  "personal-care": "Beauty & Cosmetics",
  "books-music-dvd": "Books, Music & Movies",
  automotive: "Cars, Trucks, Cycles & RVs",
  clothing: "Clothing & Accessories",
  electronics: "Computers & Electronics",
  dance: "Dance - Cheer - Gym",
  education: "Education & Supplies",
  food: "Food & Gourmet Gifts",
  gadgets: "Gadgets & Guy Stuff",
  "garden-yard": "Garden - Yard - Pool",
  gifts: "Gifts & Collectibles",
  green: "Green & Organic",
  health: "Health & Fitness",
  "home-decor": "Home Decor",
  "home-improvements": "Home Improvements",
  jewelry: "Jewelry",
  kitchen: "Kitchen & HouseWares",
  music: "Music & Instruments",
  "office-supplies": "Office Supplies",
  outdoor: "Outdoor Enthusiast",
  "party-planning": "Party Ideas & Stationary",
  pets: "Pet Supplies",
  "plus-size-clothing": "Plus Size Clothing",
  "power-sports": "Power Sports",
  spirituality: "Spirituality",
  "rugs-flooring": "Rugs & Flooring",
  seniors: "Senior Living",
  shoes: "Shoes & Footwear",
  sports: "Sports & Recreation",
  "travel-vacations": "Travel & Vacations",
  "weddings-invitations": "Weddings & Invitations",
  b2b: "Business to Business",
}
